### ISSUE TITLE
IPFS & libp2p <3 Ethereum - Roadmap of things to get everything working together nicely 👌 

### ISSUE THREAD

**Issue by diasdavid** [ipfs/notes#173]
> Following up on all the DEVCON2 conversations and collaboration

We've presented a lot of new exciting things, some of which involve getting Ethereum and DEVP2P working nicely with IPFS and libp2p. If you didn't have the chance to be there, the talks will be released soon and we will link to them here.

Meanwhile, here are the list of things that we, the IPFS and Ethereum communities, are working on to make Ethereum work nicely on top of IPFS, leveraging all of what IPLD has to offer, plus the converging the libp2p and DEVP2P stacks, towards running full Ethereum nodes in the browser and more.

# Ethereum and IPFS

## Milestone 1 - Resolve Ethereum blocks through IPFS (using IPLD)

- [x] Support for "IPLD formats" in multicodec https://github.com/multiformats/multicodec/pull/16
- [ ] Implement the upgraded IPLD resolver that is IPLD format aware through CID and knows how to use the .tree and .resolve of the IPLD formats
  - [ ] create ipld-protobuf that implements .tree and .resolve for protobuf
  - [ ] create ipld-cbor that implements .tree and .resolve for cbor
  - [ ] create ipld-eth-block that implements .tree and .resolve for ethereum blocks, rlp encoded
- [ ] Add an expactation that for the IPLD-resolver to be able to write a IPLD format to IPFS repo, this format has to have a '.serialize' func
- [ ] Enable support for more hashing functions on Multihash https://github.com/ipld/js-ipld/issues/15

# libp2p and DEVP2P

## Milestone 1 - Mount the Ethereum Wire Protocol on top of a libp2p Connection.

- [ ] Merge https://github.com/diasdavid/js-ethereum-libp2p/pull/7
- [ ] Push latest modifications to the geth client https://github.com/diasdavid/js-ethereum-libp2p/issues/9
- [ ] Get the Ethereum Wire Protocol (62+63) Implemented over a raw stream (or pull-stream) https://github.com/ethereumjs/node-devp2p-eth @axic 

# Other notes

@wanderer, @kumavis, @axic et al, it might be good to schedule a chat, next to the [Monday calls](https://github.com/ipfs/pm/issues/201) that we have every week, to sync up and make sure all the questions are answered. We can, of course, continue chatting over IRC and gitter, the calls would be just a way to check point and also invite more members in the community to participate :)

I really need to understand how https://github.com/ewasm works, so that we can have wasm-libp2p and wasm-ipfs :D

**Comment by wanderer** [comment]
I'm down for a chat. Although I haven't been successful in getting zoom to work.

**Comment by wanderer** [comment]
@diasdavid I think I missed the monday call, was in the air at that time. Will there be another meeting?

**Comment by kumavis** [comment]
I missed it too, slept all day, still adjusting

**Comment by axic** [comment]
Me too! 😃

**Comment by diasdavid** [comment]
Oh wow, we finalized the first milestone without noticing \o/
